server {
    listen 80;
    server_name mike-carvalue.linkgrid.dev;
    root /home/mike-carvalue.linkgrid.dev/public;
    index index.html index.php;

    location ~ \.php$ {
        include fastcgi_params;
        fastcgi_pass unix:/run/php-fpm/www.sock;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    }

    error_log /var/log/nginx/mike-carvalue.error.log;
    access_log /var/log/nginx/mike-carvalue.access.log;
}
